### ISSUE TITLE
Sometime accessing rmd.io/mails gives back a 500er Internal Server Error

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/rmd.io#56]
Logs: 

```[Wed Sep 18 22:13:51.459598 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714] mod_wsgi (pid=23133): Exception occurred processing WSGI script '/var/www/app/maildelay/wsgi_production.py'., referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461570 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714] Traceback (most recent call last):, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461663 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/wsgi.py", line 155, in __call__, referer: https://rmd.io/mails/
..."/var/www/app/mails/views.py", line 154, in import_mail, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461726 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     management.call_command('import', verbosity=1), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461737 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 131, in call_command, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461744 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     return command.execute(*args, **defaults), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461754 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461761 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     output = self.handle(*args, **options), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461771 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/var/www/app/mails/management/commands/import.py", line 139, in handle, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461798 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     messages = imaphelper.get_unflagged(imap_conn), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461809 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/var/www/app/mails/imaphelper.py", line 33, in get_unflagged, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461816 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     msgs.append(IMAPMessage.from_imapuid(imap_conn, uid)), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461826 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/var/www/app/mails/imaphelper.py", line 79, in from_imapuid, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461832 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     return cls(imap_conn, imapuid), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461843 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/var/www/app/mails/imaphelper.py", line 49, in __init__, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461849 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     self.msg = self._get_msg_from_imap(), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461859 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]   File "/var/www/app/mails/imaphelper.py", line 88, in _get_msg_from_imap, referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461865 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714]     data[0][1].decode(), referer: https://rmd.io/mails/
[Wed Sep 18 22:13:51.461888 2019] [wsgi:error] [pid 23133] [client 213.55.221.190:33714] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2030: invalid start byte, referer: https://rmd.io/mails/
r
```

**Comment by fujexo** [comment]
Meanwhile:
```
[Mon Mar 09 14:34:51.339557 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460] mod_wsgi (pid=32012): Exception occurred processing WSGI script '/var/www/app/maildelay/wsgi_production.py'., referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.340696 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460] Traceback (most recent call last):, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.341049 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/wsgi.py", line 155, in __call__, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.341213 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     signals.request_started.send(sender=self.__class__, environ=environ), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.341500 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 193, in send, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.341677 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     for receiver in self._live_receivers(sender), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.341847 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.342030 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     for receiver in self._live_receivers(sender), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.342301 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/views.py", line 154, in import_mail, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.342485 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     management.call_command('import', verbosity=1), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.342703 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 131, in call_command, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.342868 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     return command.execute(*args, **defaults), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.343090 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.343314 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     output = self.handle(*args, **options), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.343541 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/management/commands/import.py", line 139, in handle, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.346460 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     messages = imaphelper.get_unflagged(imap_conn), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.346647 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/imaphelper.py", line 33, in get_unflagged, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.346788 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     msgs.append(IMAPMessage.from_imapuid(imap_conn, uid)), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.346988 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/imaphelper.py", line 79, in from_imapuid, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.347206 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     return cls(imap_conn, imapuid), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.347395 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/imaphelper.py", line 49, in __init__, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.347539 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     self.msg = self._get_msg_from_imap(), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.347684 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]   File "/var/www/app/mails/imaphelper.py", line 93, in _get_msg_from_imap, referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.347830 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460]     data[0][1].decode(msg.get_charsets()[0]).encode("utf-8"), referer: https://rmd.io/mails/
[Mon Mar 09 14:34:51.348017 2020] [wsgi:error] [pid 32012] [client 95.128.36.166:53460] LookupError: unknown encoding: cp-850, referer: https://rmd.io/mails/
```

The mail: 
```
Return-Path: <v-vigala@prn.ee>
X-Original-To: yo@rmd.io
Delivered-To: maildelay@rmd.io
Received: from customer-JOJU-MCA-128-150.megared.net.mx (unknown [189.240.246.178])
	by smtp.syhosting.ch (Postfix) with ESMTP id ED3355006A
	for <yo@rmd.io>; Mon, 11 Nov 2019 17:52:43 +0100 (CET)
Message-ID: <15BF156F6FBFC515BF156F6FBFC515BF@prn.ee>
From: <v-vigala@prn.ee>
To: <yo@rmd.io>
Subject: Security Alert. Your accounts was compromised. You need change password!
Date: 11 Nov 2019 03:46:39 -0700
MIME-Version: 1.0
Content-Type: text/plain; charset="cp-850"
Content-Transfer-Encoding: 8bit
X-Mailer: Nnhiygte iivatjx 4.4

Hello!

I am a hacker who has access to your operating system.
I also have full access to your account.

I've been watching you for a few months now.
The fact is that you were infected with malware through an adult site that you visited.

If you are not familiar with this, I will explain.
Trojan Virus gives me full access and control over a computer or other device.
This means that I can see everything on your screen, turn on the camera and microphone, but you do not know about it.

I also have access to all your contacts and all your correspondence.

Why your antivirus did not detect malware?
Answer: My malware uses the driver, I update its signatures every 4 hours so that your antivirus is silent.

I made a video showing how you satisfy yourself in the left half of the screen, and in the right half you see the video that you watched.
With one click of the mouse, I can send this video to all your emails and contacts on social networks.
I can also post access to all your e-mail correspondence and messengers that you use.

If you want to prevent this,
transfer the amount of $997 to my bitcoin address (if you do not know how to do this, write to Google: "Buy Bitcoin").

My bitcoin address (BTC Wallet) is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

After receiving the payment, I will delete the video and you will never hear me again.
I give you 50 hours (more than 2 days) to pay.
I have a notice reading this letter, and the timer will work when you see this letter.

Filing a complaint somewhere does not make sense because this email cannot be tracked like my bitcoin address.
I do not make any mistakes.

If I find that you have shared this message with someone else, the video will be immediately distributed.

Best regards!
```

**Comment by eyenx** [comment]
What have you done? I just received very old mails from rmd?

**Comment by fujexo** [comment]
It didn't accept new mails, so I've restarted the server process. Seems like it didn't send out mails too. I've checked with the devs, there will be an update soon.
